project_name: how

builds:
  - id: how
    main: ./cmd/how/main.go
    binary: how
    ldflags:
      - -s -w
      - -X github.com/Codilas/how/pkg/version.Version={{.Version}}
      - -X github.com/Codilas/how/pkg/version.GitCommit={{.Commit}}
      - -X github.com/Codilas/how/pkg/version.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: tar-archive
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  - id: zip-archive
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: Codilas
    name: how

changelog:
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
