name: Documentation
description: Report an issue with the documentation
labels: ["documentation", "new"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for helping us improve our documentation.

        This issue tracker is reserved for documentation issues and improvements.
        For general questions or usage support, please visit our documentation or contact support.
  - type: dropdown
    attributes:
      label: Which part of the documentation needs attention?
      description: Select the documentation section that needs to be updated.
      options:
        - README
        - User Guide
        - Developer Guide
        - other (please specify)
  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Please provide the URL or location of the documentation that needs to be updated.
      placeholder: e.g. https://github.com/codilas/how/blob/main/README.md
    validations:
      required: true
  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What is wrong with the current documentation?
      placeholder: Describe what's wrong with the current documentation.
    validations:
      required: true
  - type: textarea
    id: suggested-content
    attributes:
      label: Suggested Content
      description: What would you like to see in the documentation?
      placeholder: Describe what you'd like to see in the documentation.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the documentation issue.
      placeholder: Add any other context about the documentation issue here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        **Note:** Ensure you have provided a **Title** for the issue. If the submit button is disabled after filling out the required fields, double-check your title. 